baseurl = "https://chrisdalke.com/"
languageCode = "en-us"
title = "Chris Dalke"
theme = "hyde-custom"
pluralizeListTitles = false
disableKinds = ["taxonomy","taxonomyTerm","sitemap"]


[params]
  description = "Full-Stack Engineer, Maker, Hardware Hacker"
  author = "Chris Dalke"

[taxonomies]


[markup.goldmark.renderer]
unsafe = true