baseurl = "https://chrisdalke.com/"
languageCode = "en-us"
title = "Chris Dalke"
theme = "hyde-custom"


  disqusShortname = "chrisdalke-com"
[params]
  description = "Software Developer, Maker"
  author = "Chris Dalke"

[taxonomies]

[markup.goldmark.renderer]
unsafe = true