[context.production.environment]
  HUGO_VERSION = "0.59.1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.59.1"


[[redirects]]
  from = "/umami.js"
  to = "https://umami.telemetryjet.com/umami.js"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/api/*"
  to = "https://umami.telemetryjet.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}