[context.production.environment]
  HUGO_VERSION = "0.59.1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.59.1"

[[headers]]
  for = "/static/DOOM.jsdos"
    [headers.values]
    Access-Control-Allow-Origin = "*"